kafka:
  config:
    bootstrap-servers: "localhost:9092"
    producer-client-id-config: "producer-2"
    producer-key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    producer-value-serializer: "ru.yandex.practicum.avro.AvroSerializer"
    consumer-group-id: "aggregator-group"
    consumer-client-id-config: "consumer-1"
    consumer-auto-commit: false
    consumer-key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    consumer-value-deserializer: "ru.yandex.practicum.avro.SensorEventDeserializer"
    consume-attempt-timeout: 100
    sensor-events-topic: "telemetry.sensors.v1"
    sensor-snapshots-topic: "telemetry.snapshots.v1"
logging:
  file:
    name: "log/aggregation-service.log"