-- =====================================================================================================================

CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    description VARCHAR(3000) NOT NULL,
    image_src VARCHAR(1000),
    product_state VARCHAR(20) NOT NULL,
    product_category VARCHAR(50) NOT NULL,
    price DOUBLE PRECISION
);

COMMENT ON TABLE products IS 'Содержит информацию о продуктах';
COMMENT ON COLUMN products.id IS 'Уникальный идентификатор продукта.';
COMMENT ON COLUMN products.name IS 'Имя продукта.';
COMMENT ON COLUMN products.description IS 'Описание продукта.';
COMMENT ON COLUMN products.image_src IS 'Ссылка на картинку во внешнем хранилище или SVG.';
COMMENT ON COLUMN products.product_state

-- =====================================================================================================================
